[phases.setup]
nixPkgs = ['python310', 'ffmpeg-headless', 'gcc']

[phases.install]
cmds = [
  'python3.10 -m venv /opt/venv',
  '. /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel',
  '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[start]
cmd = 'python http_server.py'
